#define SERVO_PIN D9
#define PEN_UP 50
#define PEN_DOWN 70
#define STEPS_PER_ROTATION 4096
#define WHEEL_TURN_DISTANCE 94.2 // (2 * M_PI * WHEEL_RADIUS)
#define STEPS_PER_MM  (STEPS_PER_ROTATION / WHEEL_TURN_DISTANCE)
#define MOTOR_LEFT_DIRECTION 1
#define MOTOR_RIGHT_DIRECTION -1
#define MOTOR_MAX_SPEED 300


#define UPLOAD_PLOT_FILENAME "/wall-plotter.data"
#define WIFI_INIT_RETRY 25

#define MOTOR_LEFT_1 D5 // IN1
#define MOTOR_LEFT_2 D6 // IN2
#define MOTOR_LEFT_3 D7 // IN3
#define MOTOR_LEFT_4 D8 // IN4
#define MOTOR_RIGHT_1 D1
#define MOTOR_RIGHT_2 D2
#define MOTOR_RIGHT_3 D3
#define MOTOR_RIGHT_4 D4
